broken: *almost* fully converted to hugo
for some reason home page has all kinds of special case logic not inline w/hugo
documentation. need to decrypt it and fix this error about index.html not
finding my shortcode as expected:
    ERROR: 2016/06/28 01:13:35 general.go:212: Error while rendering homepage:
      template: "index.html" is an incomplete or empty template;
      defined templates are:
        "_internal/shortcodes/gist.html",
        "_internal/_default/rss.xml",
        "_internal/pagination.html",
        "_internal/shortcodes/speakerdeck.html",
        "_internal/shortcodes/vimeo.html",
        "_internal/shortcodes/figure.html",
        "_internal/schema.html",
        "_default/single.html",
        "_internal/shortcodes/relref.html",
        "_internal/shortcodes/test.html",
        "_internal/_default/robots.txt",
        "_internal/shortcodes/tweet.html",
        "_internal/google_analytics_async.html",
        "post/single.html",
        "_internal/shortcodes/ref.html",
        "_internal/shortcodes/highlight.html",
        "_internal/disqus.html",
        "partials/header.html",
        "_internal/opengraph.html",
        "_internal/twitter_cards.html",
        "_internal/google_news.html",
        "shortcodes/iframe.html",
        "_internal/shortcodes/youtube.html",
        "_internal/_default/sitemap.xml",
        "shortcodes/gplusprofile.html",
        "partials/index_close.html",
        "partials/index_open.html",
        "shortcodes/script.html",
        "_internal/google_analytics.html",
        "partials/footer.html"